#build environment 
FROM node:12.18.1-alpine as build
WORKDIR /
ENV PATH /node_modules/.bin:$PATH
COPY package.json /package.json
RUN apk add bash
RUN yarn install
RUN yarn add react-scripts@3.0.1 -g
COPY . /
RUN yarn build

#production environment
FROM nginx:1.16.0-alpine
COPY --from=build /build /usr/share/nginx/html
EXPOSE 2323
CMD [“nginx”, “-g”, “daemon off;”]