#build environment 
FROM node:12.18.1-alpine
RUN mkdir -p /myapp/frontend
WORKDIR /myapp/frontend
ENV PATH myapp/frontend/node_modules/.bin:$PATH
COPY package.json /package.json
RUN yarn
RUN yarn build
COPY / /myapp/frontend