#build environment 
FROM node:12.18.1-alpine
WORKDIR ./
ENV PATH /node_modules/.bin:$PATH
COPY package.json /package.json
RUN yarn install
run yarn add react-scripts@3.0.1 -g
COPY . ./
RUN yarn build

#production environment
FROM nginx:1.16.0-alpine
COPY - from=build /build /usr/share/nginx/
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]