version: '3'
services:
  db:
    image: "postgres"
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  adminer:
    image: "adminer"
    ports:
      - "8080:8080"
  backend:
    container_name: backend
    build: ./backend
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./backend:/myapp/backend
    depends_on:
      - db
    ports:
      - 3000:3000
  frontend:
    container_name: frontend
    build: ./frontend
    image: "node:12.18.1-alpine"
    user: "node"
    working_dir: /myapp/frontend/dist
    volumes:
      - ./frontend:/myapp/frontend/dist
    ports:
      - 80:80
 #   command: "yarn build"
 #   depends_on:
 #     - backend
  # yaichi:
  #   container_name: yaichi
  #   image: mtsmfm/yaichi:1.5.0
  #   ports:
  #     - 80:3000
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
volumes:  
  database-data: