version: '3'
services:
  proxy:
    build: ./proxy
    restart: always
    ports:
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - conf.d:/etc/nginx/conf.d
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier
    environment:
      - HTTPS_METHOD=noredirect

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - conf.d:/etc/nginx/conf.d
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy

  db:
    image: "postgres"
    restart: always
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - proxy-tier
      - default

  adminer:
    image: "adminer"
    restart: always
    ports:
      - "8080:8080"
    networks:
      - proxy-tier
      - default

  backend:
    container_name: backend
    restart: always
    build: ./backend
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      DEVISE_JWT_SECRET_KEY: 784d753e9d896a894996a8c86f4666c05a97de7774a44c269fbf931fba8c4be73a029b7def71a179532e69d82079f05c0db649b430d4d432fa1111457d3fc438
      RAILS_ENV: development
    depends_on:
      - db
    networks:
      - proxy-tier
      - default
    expose:
      - 3000
    environment:
      VIRTUAL_HOST: "smartdoor-server.tadsufpr.net.br"
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: "smartdoor-server.tadsufpr.net.br"
      LETSENCRYPT_EMAIL: "alexander@ufpr.br"

  frontend:
    container_name: frontend
    restart: always
    build: ./frontend
    networks:
      - proxy-tier
      - default
    expose:
      - 5000
    environment:
      VIRTUAL_HOST: "smartdoor.tadsufpr.net.br"
      VIRTUAL_PORT: 5000
      LETSENCRYPT_HOST: "smartdoor.tadsufpr.net.br"
      LETSENCRYPT_EMAIL: "alexander@ufpr.br"
volumes:  
  database-data:
  postgres:
  certs:
  conf.d:
  vhost.d:
  html:


networks:
  proxy-tier:
    external: 
      name: nginx-proxy

